name: Build and Deploy to QA and Main

on:
  push:
    branches:
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          REPO="ghcr.io/${{ github.repository_owner }}/my-website"
          TAG=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${REPO}:${TAG} .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          REPO="ghcr.io/${{ github.repository_owner }}/my-website"
          TAG=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]')
          docker push ${REPO}:${TAG}

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'qa'

    steps:
      # 5. Deploy to QA Instance 1
      - name: Deploy to QA Instance 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.QA_INSTANCE_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            REPO="ghcr.io/${{ github.repository_owner }}/my-website"
            TAG="qa"
            docker login ghcr.io -u ${{ secrets.GHCR_ACTOR }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ${REPO}:${TAG}
            docker stop my-website || true
            docker rm my-website || true
            docker run -d --name my-website -p 80:80 ${REPO}:${TAG}

      # 6. Deploy to QA Instance 2
      - name: Deploy to QA Instance 2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.QA_INSTANCE_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            REPO="ghcr.io/${{ github.repository_owner }}/my-website"
            TAG="qa"
            docker login ghcr.io -u ${{ secrets.GHCR_ACTOR }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ${REPO}:${TAG}
            docker stop my-website || true
            docker rm my-website || true
            docker run -d --name my-website -p 80:80 ${REPO}:${TAG}

  deploy-main:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'main'

    steps:
      # 7. Deploy to Main Auto Scaling Group
      - name: Deploy to Main via Auto Scaling
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.MAIN_LB_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            REPO="ghcr.io/${{ github.repository_owner }}/my-website"
            TAG="main"
            docker login ghcr.io -u ${{ secrets.GHCR_ACTOR }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ${REPO}:${TAG}
            docker stop my-website || true
            docker rm my-website || true
            docker run -d --name my-website -p 80:80 ${REPO}:${TAG}
