name: Build and Deploy to QA and Main

on:
  push:
    branches:
      - qa
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          # Convert both repository owner and ref_name to lowercase
          OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          TAG=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/my-website:$TAG .

      # 4. Push Docker Image
      - name: Push Docker Image
        run: |
          OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          TAG=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$OWNER/my-website:$TAG

  deploy-QA:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'qa'

    steps:
      # 5. Deploy to QA Instance 1
      - name: Deploy to QA Instance 1
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.QA1_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_ACTOR }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/my-website:qa
            docker stop my-website || true
            docker rm my-website || true
            docker run -d --name my-website -p 80:80 ghcr.io/${{ github.repository_owner }}/my-website:qa

      # 6. Deploy to QA Instance 2
      - name: Deploy to QA Instance 2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.QA2_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_ACTOR }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/my-website:qa
            docker stop my-website || true
            docker rm my-website || true
            docker run -d --name my-website -p 80:80 ghcr.io/${{ github.repository_owner }}/my-website:qa

  deploy-main:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'main'

    steps:
      # 7. Update Main Image for Auto Scaling Group
      - name: Update Main Docker Image for ASG
        run: |
          echo "The latest Docker image has been built and pushed to the registry. Auto Scaling Group will pull it automatically."